[{"name":"点击相关","summary":"简介","url":"apiurl","level":0,
"functions":[
    {"name":"模拟点击此位置","icon":"","contentform":"click(%pointx,%pointy)"}
    ]
},
  {"name":"按键模拟","summary":"模拟物理按键操作","url":"","level":0,
"functions":[{
    "name":"模拟返回","icon":"","contentform":"back()",
},{
    "name":"模拟返回桌面","icon":"","contentform":"home()",
}
]}]